import re

missing_en = {
    "promo_active": "✅ Active code: -{discount}€ applied",
    "use_my_balance": "💰 Use my balance",
    "available_balance": "Available: {amount}€",
    "del_tag_hall": "🏢 I'll wait in the lobby",
    "del_tag_discrete": "🤫 Do not ring (Discreet)",
    "leave_empty_asap": "Leave empty for ASAP delivery",
    "no_saved_addr": "No saved addresses.",
    "click_addr_edit": "💡 Click an address to edit or set as default",
    "add_address": "ADD AN ADDRESS",
    "addr_home": "Home",
    "addr_office": "Office",
    "addr_friend": "Friend",
    "addr_hotel": "Hotel",
    "addr_other": "Other",
    "addr_type": "Address type",
    "suppliers": "Suppliers",
    "dom_erreur_lors_du_tri": "Sorting error",
    "dom_mise_jour": "Updating...",
    "dom_synchronisation_d_ma": "Synchronization started...",
    "dom_profil_mis_jour": "Profile updated!",
    "dom_utilisateur_a_bloqu": "User blocked the bot!",
    "dom_utilisateur_actif": "User active.",
    "dom_cr_dit_mis_jour": "Credit updated!",
    "dom_points_mis_jour": "Points updated!",
    "dom_utilisateur_approuv": "User approved!",
    "dom_stock_mis_jour_avec": "Stock updated successfully!",
    "dom_produit_valid_et_mi": "✅ Product validated and put on sale!",
    "dom_livreur_assign_avec": "Courier assigned successfully!",
    "dom_logo_mis_jour_avec_s": "Logo updated successfully!",
    "dom_erreur_lors_de_l_upl": "Upload error",
    "dom_param_tres_mis_jour": "Settings updated!",
    "dom_utilisateur_supprim": "User deleted",
    "dom_commande_supprim_e": "Order deleted",
    "dom_base_de_donn_es_r_i": "✅ Database reset successfully.",
    "dom_erreur_lors_de_la_s": "❌ Error during deletion.",
    "dom_client_introuvable": "Client not found",
    "dom_ouverture_telegram_d": "Opening Telegram directly...",
    "dom_identifiant_telegram": "Telegram ID not found",
    "dom_cet_utilisateur_est": "This user is already a supplier!",
    "dom_produit_transf_r_av": "✅ Product transferred to catalog successfully!",
    "dom_produit_mis_jour": "✅ Product updated",
    "dom_panier_vide": "Empty cart!",
    "dom_veuillez_entrer_une": "Please enter a delivery address!",
    "dom_commandes_envoy_es": "🚀 Orders sent!",
    "dom_r_ponse_envoy_e": "Reply sent",
    "dom_erreur_envoi_r_ponse": "Error sending reply",
    "dom_avis_supprim": "Review deleted ✅",
    "dom_erreur_lors_de_la_su": "Error during deletion ❌",
    "dom_impossible_de_charge": "Unable to load products.",
    "dom_utilisateur_ajout_av": "User added successfully!",
    "dom_diffusion_charg_e_da": "Broadcast loaded",
    "dom_log_supprim": "Log deleted",
    "dom_crivez_un_message_o": "Write a message or add media.",
    "dom_diffusion_lanc_e": "🚀 Broadcast started!",
    "dom_aucune_donn_e_export": "No data to export.",
    "dom_nom_et_prix_requis": "Name and price required",
    "dom_vous_devez_obligatoi": "You must specify available stock quantity.",
    "dom_produit_sauvegard": "Product saved!",
    "dom_format_non_reconnu": "Unrecognized format",
    "dom_produit_supprim": "🗑 Product deleted",
    "dom_mise_jour_de_l_ordre": "Updating order",
    "dom_ordre_enregistr": "Order saved!",
    "dom_le_nom_est_obligatoi": "Name is mandatory"
}

missing_es = {
    "promo_active": "✅ Código activo: -{discount}€ aplicado",
    "use_my_balance": "💰 Usar mi saldo",
    "available_balance": "Disponible: {amount}€",
    "del_tag_hall": "🏢 Esperaré en el vestíbulo",
    "del_tag_discrete": "🤫 No tocar el timbre (Discreto)",
    "leave_empty_asap": "Dejar vacío para entrega lo antes posible",
    "no_saved_addr": "No hay direcciones guardadas.",
    "click_addr_edit": "💡 Haz clic en una dirección para editar o fijar por defecto",
    "add_address": "AÑADIR DIRECCIÓN",
    "addr_home": "Casa",
    "addr_office": "Oficina",
    "addr_friend": "Amigo",
    "addr_hotel": "Hotel",
    "addr_other": "Otro",
    "addr_type": "Tipo de dirección",
    "suppliers": "Proveedores",
    "dom_erreur_lors_du_tri": "Error de clasificación",
    "dom_mise_jour": "Actualizando...",
    "dom_synchronisation_d_ma": "Sincronización iniciada...",
    "dom_profil_mis_jour": "¡Perfil actualizado!",
    "dom_utilisateur_a_bloqu": "¡El usuario ha bloqueado al bot!",
    "dom_utilisateur_actif": "Usuario activo.",
    "dom_cr_dit_mis_jour": "¡Crédito actualizado!",
    "dom_points_mis_jour": "¡Puntos actualizados!",
    "dom_utilisateur_approuv": "¡Usuario aprobado!",
    "dom_stock_mis_jour_avec": "¡Stock actualizado con éxito!",
    "dom_produit_valid_et_mi": "✅ ¡Producto validado y puesto a la venta!",
    "dom_livreur_assign_avec": "¡Repartidor asignado con éxito!",
    "dom_logo_mis_jour_avec_s": "¡Logo actualizado con éxito!",
    "dom_erreur_lors_de_l_upl": "Error de subida",
    "dom_param_tres_mis_jour": "¡Ajustes actualizados!",
    "dom_utilisateur_supprim": "Usuario eliminado",
    "dom_commande_supprim_e": "Pedido eliminado",
    "dom_base_de_donn_es_r_i": "✅ Base de datos restablecida con éxito.",
    "dom_erreur_lors_de_la_s": "❌ Error al eliminar.",
    "dom_client_introuvable": "Cliente no encontrado",
    "dom_ouverture_telegram_d": "Abriendo Telegram directamente...",
    "dom_identifiant_telegram": "ID de Telegram no encontrado",
    "dom_cet_utilisateur_est": "¡Este usuario ya es proveedor!",
    "dom_produit_transf_r_av": "✅ ¡Producto transferido al catálogo con éxito!",
    "dom_produit_mis_jour": "✅ Producto actualizado",
    "dom_panier_vide": "¡Carrito vacío!",
    "dom_veuillez_entrer_une": "¡Por favor, introduzca una dirección de entrega!",
    "dom_commandes_envoy_es": "🚀 ¡Pedidos enviados!",
    "dom_r_ponse_envoy_e": "Respuesta enviada",
    "dom_erreur_envoi_r_ponse": "Error enviando respuesta",
    "dom_avis_supprim": "Reseña eliminada ✅",
    "dom_erreur_lors_de_la_su": "Error al eliminar ❌",
    "dom_impossible_de_charge": "No se pueden cargar los productos.",
    "dom_utilisateur_ajout_av": "¡Usuario añadido con éxito!",
    "dom_diffusion_charg_e_da": "Difusión cargada",
    "dom_log_supprim": "Registro eliminado",
    "dom_crivez_un_message_o": "Escriba un mensaje o añada multimedia.",
    "dom_diffusion_lanc_e": "🚀 ¡Difusión iniciada!",
    "dom_aucune_donn_e_export": "No hay datos para exportar.",
    "dom_nom_et_prix_requis": "Nombre y precio requeridos",
    "dom_vous_devez_obligatoi": "Debe especificar la cantidad de stock disponible.",
    "dom_produit_sauvegard": "¡Producto guardado!",
    "dom_format_non_reconnu": "Formato no reconocido",
    "dom_produit_supprim": "🗑 Producto eliminado",
    "dom_mise_jour_de_l_ordre": "Actualizando pedido",
    "dom_ordre_enregistr": "¡Pedido guardado!",
    "dom_le_nom_est_obligatoi": "El nombre es obligatorio"
}

missing_de = {
    "promo_active": "✅ Aktiver Code: -{discount}€ angewendet",
    "use_my_balance": "💰 Mein Guthaben verwenden",
    "available_balance": "Verfügbar: {amount}€",
    "del_tag_hall": "🏢 Ich warte in der Lobby",
    "del_tag_discrete": "🤫 Nicht klingeln (Diskret)",
    "leave_empty_asap": "Für sofortige Lieferung leer lassen",
    "no_saved_addr": "Keine gespeicherten Adressen.",
    "click_addr_edit": "💡 Klicken Sie auf eine Adresse, um sie zu bearbeiten",
    "add_address": "ADRESSE HINZUFÜGEN",
    "addr_home": "Zuhause",
    "addr_office": "Büro",
    "addr_friend": "Freund",
    "addr_hotel": "Hotel",
    "addr_other": "Andere",
    "addr_type": "Adresstyp",
    "suppliers": "Lieferanten",
    "dom_erreur_lors_du_tri": "Sortierfehler",
    "dom_mise_jour": "Aktualisierung...",
    "dom_synchronisation_d_ma": "Synchronisation gestartet...",
    "dom_profil_mis_jour": "Profil aktualisiert!",
    "dom_utilisateur_a_bloqu": "Benutzer hat den Bot blockiert!",
    "dom_utilisateur_actif": "Benutzer aktiv.",
    "dom_cr_dit_mis_jour": "Guthaben aktualisiert!",
    "dom_points_mis_jour": "Punkte aktualisiert!",
    "dom_utilisateur_approuv": "Benutzer genehmigt!",
    "dom_stock_mis_jour_avec": "Bestand erfolgreich aktualisiert!",
    "dom_produit_valid_et_mi": "✅ Produkt validiert und zum Verkauf freigegeben!",
    "dom_livreur_assign_avec": "Kurier erfolgreich zugewiesen!",
    "dom_logo_mis_jour_avec_s": "Logo erfolgreich aktualisiert!",
    "dom_erreur_lors_de_l_upl": "Uploadfehler",
    "dom_param_tres_mis_jour": "Einstellungen aktualisiert!",
    "dom_utilisateur_supprim": "Benutzer gelöscht",
    "dom_commande_supprim_e": "Bestellung gelöscht",
    "dom_base_de_donn_es_r_i": "✅ Datenbank erfolgreich zurückgesetzt.",
    "dom_erreur_lors_de_la_s": "❌ Fehler beim Löschen.",
    "dom_client_introuvable": "Kunde nicht gefunden",
    "dom_ouverture_telegram_d": "Telegram wird direkt geöffnet...",
    "dom_identifiant_telegram": "Telegram-ID nicht gefunden",
    "dom_cet_utilisateur_est": "Dieser Benutzer ist bereits Lieferant!",
    "dom_produit_transf_r_av": "✅ Produkt erfolgreich in den Katalog übertragen!",
    "dom_produit_mis_jour": "✅ Produkt aktualisiert",
    "dom_panier_vide": "Leerer Warenkorb!",
    "dom_veuillez_entrer_une": "Bitte Lieferadresse eingeben!",
    "dom_commandes_envoy_es": "🚀 Bestellungen gesendet!",
    "dom_r_ponse_envoy_e": "Antwort gesendet",
    "dom_erreur_envoi_r_ponse": "Fehler beim Senden der Antwort",
    "dom_avis_supprim": "Bewertung gelöscht ✅",
    "dom_erreur_lors_de_la_su": "Fehler beim Löschen ❌",
    "dom_impossible_de_charge": "Produkte können nicht geladen werden.",
    "dom_utilisateur_ajout_av": "Benutzer erfolgreich hinzugefügt!",
    "dom_diffusion_charg_e_da": "Rundsendung geladen",
    "dom_log_supprim": "Log gelöscht",
    "dom_crivez_un_message_o": "Schreiben Sie eine Nachricht oder fügen Sie Medien hinzu.",
    "dom_diffusion_lanc_e": "🚀 Rundsendung gestartet!",
    "dom_aucune_donn_e_export": "Keine Daten zum Exportieren.",
    "dom_nom_et_prix_requis": "Name und Preis erforderlich",
    "dom_vous_devez_obligatoi": "Verfügbare Bestandsmenge muss angegeben werden.",
    "dom_produit_sauvegard": "Produkt gespeichert!",
    "dom_format_non_reconnu": "Unerkanntes Format",
    "dom_produit_supprim": "🗑 Produkt gelöscht",
    "dom_mise_jour_de_l_ordre": "Bestellung wird aktualisiert",
    "dom_ordre_enregistr": "Bestellung gespeichert!",
    "dom_le_nom_est_obligatoi": "Name ist obligatorisch"
}

with open('web/js/translations.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

def inject_trans(lang_code, translations):
    global js_content
    match = re.search(f'"{lang_code}":\s*\\{{', js_content)
    if not match: return
    start_idx = match.end()
    
    injections = []
    for k, v in translations.items():
        if f'"{k}"' not in js_content[start_idx:start_idx+8000]:
            injections.append(f'        "{k}": "{v}",')
            
    if injections:
        injection_str = "\n".join(injections) + "\n"
        js_content = js_content[:start_idx] + "\n" + injection_str + js_content[start_idx:]

inject_trans('en', missing_en)
inject_trans('es', missing_es)
inject_trans('de', missing_de)

with open('web/js/translations.js', 'w', encoding='utf-8') as f:
    f.write(js_content)
